[package]
name = "ntz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float_eq = "0.6.0"
num-traits = "0.2.14"
paste = "1.0.5"
